define(`dev_pkgs', patsubst(dev_pkgs, ` cmocka', `'))
define(`CMOCKA_VER', `1.0.1')
define(`CMOCKA_DEPS', `wget xz-utils cmake')
define(`extra_dev', `systemd')
define(`INSTALL', INSTALL `--force-yes')
define(`PREINSTALL', `RUN /bin/echo -e "deb http://archive.debian.org/debian jessie main\ndeb http://archive.debian.org/debian-security jessie/updates main" >/etc/apt/sources.list')
define(`UPDATE', `apt-get -o Acquire::Check-Valid-Until=false -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true update')
define(`asan', `libasan1')
