# Copyright (c) 2022 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later
FROM BASE:TAG
LABELS
RUN_CMD(UPDATE)
RUN_CMD(UPDATE && \
    INSTALL \
    RUNTIME_PKGS \
    RUNTIME_LIBS)
RUN_CMD(CLEAN)
VOLUME /build
WORKDIR /build/tests
ENTRYPOINT ["make"]
