#! /bin/bash

trap 'echo error in $BASH_COMMAND >&2; exit 1' ERR
set -E

#DISTS=(buster bullseye)
DISTS=(fedora-36)
#ARCHS=(ppc64le s390x aarch64)
ARCHS=("")

case $1 in
    src)
	PKG=libedit-dev
	BASE=multipath-build
	;;
    bin)
	PKG=libedit2
	BASE=multipath-run
	;;
esac

[[ $PKG ]]
REG=docker.io/mwilck

modify() {
    local OS=$1
    local ARCH=$2

    case $OS in
	buster|bullseye|focal|jessie|bionic|sid|xenial)
	    case $ARCH in
		ppc64le)
		    ARCHX=":ppc64el";;
		aarch64)
		    ARCHX=":arm64";;
		"")
		    ARCHX=;;
		*)
		    ARCHX=":$ARCH";;
	    esac
	    CMD=/usr/bin/apt-get
	    ARGS=(install --yes $PKG$ARCHX)
	    ;;
	fedora-*)
	    case $PKG in
		*-dev)
		    # -dev -> -devel
		    PKG=${PKG}el;;
	    esac
	    CMD=/usr/bin/dnf
	    ARGS=(-y install $PKG)
	    ;;
    esac

    CNT=$BASE-$OS${ARCH:+-$ARCH}
    podman run --name $CNT -it --entrypoint=$CMD $REG/$CNT "${ARGS[@]}"
    podman commit $CNT $CNT
    podman push $CNT $REG/$CNT
    podman rm $CNT
    podman image rm $CNT
}

for OS in "${DISTS[@]}"; do
    for ARCH in "${ARCHS[@]}"; do
	echo === $BASE $OS $ARCH $PKG === >&2
	modify $OS $ARCH
    done
done
