---
name: build cross-compile containers for stable distros
on:
  push:
    branches:
      - master

jobs:
  build-cross:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian_cross-bullseye
          - debian_cross-bookworm
          - debian_cross-trixie
        arch:
          - arm64
          - ppc64le
          - s390x
          - armhf
        exclude:
          - os: debian_cross-bullseye
            arch: ppc64le
          - os: debian_cross-bullseye
            arch: s390x

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Dockerfile
        id: m4
        run: |
          mkdir ./container
          m4 -I m4 -D DISTRO=${{ matrix.os }} \
              -D ARCH=${{ matrix.arch }} \
             header.m4 dockerfile.m4 >./container/Dockerfile
          cat ./container/Dockerfile

      - name: Copy files
        run: |
          [ ! -d ./${{ matrix.os }} ] || \
          ln -v -t ./container ./${{ matrix.os }}/*

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.os }}-${{ matrix.arch }}
          key: multipath-cross-${{ matrix.os }}-${{ matrix.arch }}

      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: ./container
          push: true
          tags: ghcr.io/mwilck/multipath-cross-${{ matrix.os }}-${{ matrix.arch }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.os }}-${{ matrix.arch }}
          cache-to: type=local,dest=/tmp/.new-buildx-cache-${{ matrix.os }}-${{ matrix.arch }}

      - name: Move cache
        # Avoid cache growing too large
        # https://github.com/docker/build-push-action/issues/252
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.os }}-${{ matrix.arch }}
          mv /tmp/.new-buildx-cache-${{ matrix.os }}-${{ matrix.arch }} \
             /tmp/.buildx-cache-${{ matrix.os }}-${{ matrix.arch }}

  build-runner:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-bullseye
          - debian-bookworm

    steps:

      - name: set arch list
        run: >-
          echo PLATFORMS=linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7
          >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest

      - name: Create Dockerfile
        id: m4
        run: |
          mkdir ./container
          m4 -I m4 -D DISTRO=${{ matrix.os }} \
             header.m4 dockerfile.m4 >./container/Dockerfile
          cat ./container/Dockerfile

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.os }}
          key: runners-${{ matrix.os }}

      - name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: ./container
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ghcr.io/mwilck/multipath-run-${{ matrix.os }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.os }}
          cache-to: type=local,dest=/tmp/.new-buildx-cache-${{ matrix.os }}

      - name: Move cache
        # Avoid cache growing too large
        # https://github.com/docker/build-push-action/issues/252
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.os }}
          mv /tmp/.new-buildx-cache-${{ matrix.os }} \
             /tmp/.buildx-cache-${{ matrix.os }}
