name: create images for compilation
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [buster, jessie, sid]
        arch: ['', '-i386']

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-${{ matrix.os }}${{ matrix.arch }}
          key: build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/${{ matrix.os }}${{ matrix.arch}}
          push: true
          tags: mwilck/multipath-build-${{ matrix.os }}${{ matrix.arch}}:latest
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.os }}${{ matrix.arch }}
          cache-to: type=local,dest=/tmp/.new-buildx-cache-${{ matrix.os }}${{ matrix.arch }}
         # Temp fix
          # https://github.com/docker/build-push-action/issues/252

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.os }}${{ matrix.arch }}
          mv /tmp/.new-buildx-cache-${{ matrix.os }}${{ matrix.arch }} /tmp/.buildx-cache-${{ matrix.os }}${{ matrix.arch }}
