name: build foreign arch containers
on:
  push:
    branches:
      - master

jobs:
  build-containers:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os:
          - buster
          - bullseye
        arch:
          - s390x
          - ppc64le
          - aarch64
        exclude:
          - os: buster
            arch: s390x
          - os: buster
            arch: ppc64le

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers for builder
        uses: actions/cache@v2
        with:
          path: /tmp/.builder-cache-${{ matrix.os }}-${{ matrix.arch }}
          key: build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}

      - name: Cache Docker layers for runner
        uses: actions/cache@v2
        with:
          path: /tmp/.runner-cache-${{ matrix.os }}-${{ matrix.arch }}
          key: runner-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            runner-${{ runner.os }}

      - name: Build and push builder
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/${{ matrix.os }}-${{ matrix.arch}}
          push: true
          tags: mwilck/multipath-build-${{ matrix.os }}-${{ matrix.arch}}:latest
          cache-from: type=local,src=/tmp/.builder-cache-${{ matrix.os }}-${{ matrix.arch }}
          cache-to: type=local,dest=/tmp/.new-builder-cache-${{ matrix.os }}-${{ matrix.arch }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.arch }}

      - name: Build and push runner
        uses: docker/build-push-action@v2
        with:
          context: ./Docker/${{ matrix.os }}-${{ matrix.arch }}/Runner
          push: true
          tags: mwilck/multipath-run-${{ matrix.os }}-${{ matrix.arch }}:latest
          cache-from: type=local,src=/tmp/.runner-cache-${{ matrix.os }}-${{ matrix.arch }}
          cache-to: type=local,dest=/tmp/.new-runner-cache-${{ matrix.os }}-${{ matrix.arch }}

          # Temp fix
          # https://github.com/docker/build-push-action/issues/252

      - name: Move caches
        run: |
          rm -rf /tmp/.builder-cache-${{ matrix.os }}-${{ matrix.arch }}
          mv /tmp/.new-builder-cache-${{ matrix.os }}-${{ matrix.arch }} /tmp/.builder-cache-${{ matrix.os }}-${{ matrix.arch }}
          rm -rf /tmp/.runner-cache-${{ matrix.os }}-${{ matrix.arch }}
          mv /tmp/.new-runner-cache-${{ matrix.os }}-${{ matrix.arch }} /tmp/.runner-cache-${{ matrix.os }}-${{ matrix.arch }}

